[book]
title = "new-project" # TODO: fill in your project name
authors = ["Bytecode Alliance contributors"]
language = "en"
multilingual = false

src = "src"

[build]
build-dir = "dist"

[output.html]
git-repository-url = "https://github.com/bytecodealliance/<your project>" # TODO: fill in your project name

[preprocessor.alerts]

[output.linkcheck]
