name: test

on:
  merge_group:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "latest"

      - name: Cache npm install
        id: cache-node-modules
        working-directory: js
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('js/package-lock.json') }}
          path: |
            node_modules

      - name: Install NPM packages
        working-directory: js
        run: npm install

  run:
    runs-on: ubuntu-latest
    needs:
      - deps
    strategy:
      matrix:
        script:
          - lint
          - build
          - test
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "latest"

      - name: Restore npm cache
        id: cache-node-modules
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('js/package-lock.json') }}

      - name: Install NPM packages
        run: npm install

      - name: Run npm script ${{ matrix.script }}
        working-directory: js
        run: |
          npm run ${{ matrix.script }}
