name: test-js

on:
  merge_group:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "latest"

      - name: Cache npm install
        id: cache-node-modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('js/package-lock.json') }}
          path: |
            js/node_modules

      - name: Install NPM packages
        working-directory: js
        run: npm install

  run:
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest
    needs:
      - deps
    strategy:
      matrix:
        script:
          - lint
          - build
          - test
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "latest"

      - name: Restore npm cache
        id: cache-node-modules
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('js/package-lock.json') }}
          path: |
            js/node_modules

      - name: Install NPM packages
        working-directory: js
        run: npm install

      - name: Run npm script ${{ matrix.script }}
        working-directory: js
        run: |
          npm run ${{ matrix.script }}
