name: test-js

on:
  merge_group:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "latest"

      - name: Cache npm install
        id: cache-node-modules
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('js/package-lock.json') }}
          path: |
            js/node_modules

      - name: Install NPM packages
        working-directory: js
        run: npm install

  run:
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest
    needs:
      - deps
    strategy:
      matrix:
        script:
          - lint
          - build
          - test
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "latest"

      - name: Restore npm cache
        id: cache-node-modules
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('js/package-lock.json') }}
          path: |
            js/node_modules

      - name: Install NPM packages
        working-directory: js
        run: npm install

      - name: Run npm script ${{ matrix.script }}
        working-directory: js
        run: |
          npm run ${{ matrix.script }}
